# Generated by Django 6.1 on 2026-09-15 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='collectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('address', models.TextField()),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('collected', 'collected'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waste_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecategory')),
            ],
        ),
    ]
